---
title: "removal_exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("setup.R")
```

```{r}
data.priming.long %>%
  filter(amoA %in% non_manured_favored$Species) %>% 
  group_by(amoA, fert_level) %>% 
  summarize(avg_ct = mean(deltaCT)) %>% 
  mutate(amoA = str_sub(amoA, -3)) %>% 
  ggplot(aes(amoA, avg_ct)) +
  geom_col() +
  facet_wrap(~ fert_level) + 
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.text = element_markdown(size = 12),
    legend.title = element_markdown(size = 12, hjust = 0),
    # axis.text.x = element_text(size = 14),
    # axis.text.y = element_text(size = 14),
    # axis.title.x = element_text(size = 12),
    # axis.title.y = element_text(size = 12),
    strip.background = element_rect(size = 1, color = "black", fill = "NA"),
    panel.grid = element_line(color = "gray95"),
    panel.border = element_rect(color = "black", size = 1, fill = NA)
  ) +
  geom_hline(yintercept = 27, color = "red", linetype = "dashed") +
  scale_y_continuous(limits = c(0, 30), expand = expansion(add = c(0, 0))) +
  labs(y = "Average CT")
```

```{r}
data.priming.long %>% 
  group_by(fert_level, amoA) %>% 
  summarize(avg_ct = mean(deltaCT)) %>% 
  mutate(amoA = str_sub(amoA, -3)) %>%
  pivot_wider(names_from = "fert_level", values_from = "avg_ct") %>% 
  filter(`0` > 20 & `336` > 20)
  ggplot(aes(amoA, avg_ct)) +
  geom_col() +
  facet_wrap(~ fert_level) + 
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.text = element_markdown(size = 12),
    legend.title = element_markdown(size = 12, hjust = 0),
    # axis.text.x = element_text(size = 14),
    # axis.text.y = element_text(size = 14),
    # axis.title.x = element_text(size = 12),
    # axis.title.y = element_text(size = 12),
    strip.background = element_rect(size = 1, color = "black", fill = "NA"),
    panel.grid = element_line(color = "gray95"),
    panel.border = element_rect(color = "black", size = 1, fill = NA)
  ) +
  geom_hline(yintercept = 27, color = "red", linetype = "dashed") +
  scale_y_continuous(limits = c(0, 30), expand = expansion(add = c(0, 0))) +
  labs(y = "Average CT")
```

```{r}
non_detect_counts <- data.raw.long %>%
  group_by(fert_level, amoA) %>% 
  count(CT == 40) %>% 
  rename(non_detect = `CT == 40`) %>%
  filter(non_detect == TRUE) 

removes <- non_detect_counts %>% 
  pivot_wider(names_from = fert_level, values_from = n, names_prefix = "fert.") %>%
  filter(fert.0 > 30 & fert.336 > 30) %>%
  pivot_longer(cols = fert.0:fert.336, names_to = "fert_level", values_to = "n")

removes %>% 
  mutate(amoA = str_sub(amoA, -3)) %>% 
  mutate(favored = case_when(
    amoA %in% c("006", "038", "064", "069", "071") ~ "Nothing",
    amoA %in% c("021", "028", "030", "048", "073", "075", "076", "077", "078") ~ "Non-fertilized",
    amoA %in% c("040", "050", "053") ~ "Fourth quadrant",
    TRUE ~ "First quadrant"
  )) %>% 
  mutate(fert_level = str_sub(fert_level, start = 6)) %>% 
  ggplot(aes(amoA, n, fill = favored )) +
  geom_col() +
  facet_wrap(~ fert_level) + 
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.text = element_markdown(size = 12),
    legend.title = element_markdown(size = 12, hjust = 0),
    strip.background = element_rect(size = 1, color = "black", fill = "NA"),
    panel.grid = element_line(color = "gray95"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.border = element_rect(color = "black", size = 1, fill = NA)
  ) +
  scale_fill_viridis_d(begin = 0, end = 0.5) +
  scale_y_continuous(limits = c(0, 50), expand = expansion(add = c(0, 0))) +
  scale_x_discrete(limits = rev) + 
  coord_flip() + 
  labs(
    y = "Number of samples with > 30 non-detects",
    title = "Fertilizer level",
    fill = "Favored by..."
  )
```
